trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo hello from Linux
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: brew bundle Brewfile1
  - script: brew bundle Brewfile2
  - script: brew bundle Brewfile3
  - script: brew bundle Brewfile4
  - script: brew bundle Brewfile5
  - script: brew bundle Brewfile6
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: echo hello from Windows
